---
layout: reading
link: https://www.goodreads.com/book/show/246937.The_Answer_to_How_Is_Yes
full_title: 'The Answer to How Is Yes: Acting on What Matters'
short_title: The Answer to How Is Yes
title: The Answer to How Is Yes
tags:
- entrepreneurship
rating: 3
with_note: false
book_author: Peter Block
---

This was a slow read. I understand why some people might find it too
hard or boring to read, but I liked it a lot.

It reminded me of some texts of Tao Te Ching, sometimes contradictory
sometimes seemingly stupid.

He shows us our obsession with methods, tools and techniques (the
question of how), and how this obsession actually prevents us from
doing the things we believe in.

It's a book to read over the time of a whole year. The repitition can
get boring when reading the book too fast without taking the time to
contemplate and really unfold your own inner thoughts on the concepts.

Really, demanding too much too quickly would have prevented me from
really grapsing the topics in the book and I will have to come back to
further my understanding.

Also you should not expect hands-on advice.

* Summary

- ::
