language: ruby
rvm:
- 2.3.3
env:
  global:
    # speeds up installation of html-proofer:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - bundle install
  - pip install --user awscli
  - git submodule update --init --recursive _gitsubmodules/emacs.d
script: ruby prepare_files.rb && ruby grab_goodreads.rb && jekyll build
branches:
  only:
  - master
exclude: [vendor]
sudo: false
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: ./_site
  region: $AWS_DEFAULT_REGION
  cache_control: "max-age=21600"
  acl: public_read
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
