language: ruby
rvm:
- 2.3.3
env:
  global:
    # speeds up installation of html-proofer:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - bundle install
  - pip install awscli
script: ruby grab_goodreads.rb && jekyll build
branches:
  only:
  - master
exclude: [vendor]
sudo: false
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: ./_site
  region: eu-central-1
  cache_control: "max-age=21600"
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
