title: andersen.berlin
email: arthur@andersen.berlin
description: >-
  Superstuff
baseurl: ""
url: "https://www.andersen.berlin"
permalink: pretty

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-assets

sass:
  sass_dir: _sass
  style: compressed

assets:
  digest: true
